codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 90%
        threshold: 5%

  # 커버리지 계산에서 제외할 파일들
  ignore:
    - "lib/config/firebase_options_*.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/**/*"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: new
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true
  hide_comment_details: false
  after_n_builds: 1            
