name: rubbit_client
description: "diary service with ai."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_messaging: ^14.7.3
  cloud_firestore: ^4.12.1

  # 상태 관리
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # 네트워크 및 API
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # 로컬 저장소
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # 환경 설정
  flutter_dotenv: ^5.1.0
  package_info_plus: ^4.2.0

  # UI/UX
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # 유틸리티
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # 린트 및 코드 품질
  flutter_lints: ^5.0.0

  # 테스트 도구
  mockito: ^5.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/splash_screen.png